In [1]:
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print (sess.run(hello))

b'Hello, TensorFlow!'


In [18]:
a = tf.constant(2)
b = tf.constant(3)
with tf.Session() as sess:
    print ("a=2, b=3")
    print ("Addition with constants: %i" % sess.run(a+b))
    print ("Multiplication with constants: %i" % sess.run(a*b))

a=2, b=3
Addition with constants: 5
Multiplication with constants: 6


In [19]:
sess = tf.Session()
sess.run(tf.constant(100)+tf.constant(7878))
sess.run(tf.constant("Hello, TensorFlow")+tf.constant(" By Python"))

b'Hello, TensorFlow By Python'

In [21]:
a = tf.placeholder(tf.int16)
b = tf.placeholder(tf.int16)
add = tf.add(a, b)
mul = tf.multiply(a, b)
with tf.Session() as sess:
    # Run every operation with variable input
    print ("Addition with variables: %i" % sess.run(add, feed_dict={a: 2, b: 3}))
    print ("Multiplication with variables: %i" % sess.run(mul, feed_dict={a: 2, b: 3}))

Addition with variables: 5
Multiplication with variables: 6


In [5]:
a = tf.constant([1.0, 2.0], name = 'a')
b = tf.constant([2.0, 3.0], name = 'b')
result = a + b
sess = tf.Session()
sess.run(result)

array([ 3.,  5.], dtype=float32)

In [15]:
a = tf.constant([1.0, 2.0], name = 'a')
b = tf.constant([2.0, 3.0], name = 'b')
result = a + b
print(tf.get_default_graph)

<function get_default_graph at 0x0000000007DF4EA0>


In [29]:

g1 = tf.Graph()
with g1.as_default():
    # 初始化为0
    init = tf.zeros(shape=[1])
    v = tf.get_variable("v", initializer=init)

g2 = tf.Graph()
with g2.as_default():
    # 初始化为1
    init = tf.ones(shape=[1])
    v = tf.get_variable("v", initializer=init)

with tf.Session(graph=g1) as sess:
    tf.initialize_all_variables().run()
    with tf.variable_scope("", reuse=True):
        print(sess.run(tf.get_variable("v")))


with tf.Session(graph=g2) as sess:
    tf.initialize_all_variables().run()
    with tf.variable_scope("", reuse=True):
        print(sess.run(tf.get_variable("v")))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
[ 0.]
Instructions for updating:
Use `tf.global_variables_initializer` instead.
[ 1.]


In [48]:
import tensorflow as tf

a = tf.constant([1.0, 2.0, 3.0], name = 'a')
b = tf.constant([4.0, 4.0, 4.0], name = 'b')

g = tf.Graph()
# 指定计算运行的设备，这里指定为显卡
with g.device('/gpu:0'):
    result = tf.add(a, b, name = 'add')
    print(result)
    # 通过会话来执行定义好的计算
    with tf.Session().as_default():
        print(result.eval())

Tensor("add_27:0", shape=(3,), dtype=float32)
[ 5.  6.  7.]


In [53]:
import tensorflow as tf

a = tf.constant([1.0, 2.0, 3.0], name = 'a')
b = tf.constant([4.0, 4.0, 4.0], name = 'b')
result = tf.add(a, b, name = 'add')

sess = tf.Session()
with sess.as_default():
    print(result.eval())

# 同上
print(sess.run(result))
print(result.eval(session = sess))


[ 5.  6.  7.]
[ 5.  6.  7.]
[ 5.  6.  7.]


In [64]:
# 使用随机数来生成一个矩阵变量
weight = tf.Variable(tf.random_normal([2, 3], stddev=2))
print(weight)

# 生成一个全0的矩阵
weight2 = tf.Variable(tf.zeros([2, 3], tf.int32))
print(weight2)

# 生成一个全1的矩阵
weight3 = tf.Variable(tf.ones([2, 3], tf.int32))
print(weight3)

# 生成一个给定数字的矩阵
weight4 = tf.Variable(tf.fill([2, 3],9))
print(weight4)

<tf.Variable 'Variable_13:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'Variable_14:0' shape=(2, 3) dtype=int32_ref>
<tf.Variable 'Variable_15:0' shape=(2, 3) dtype=int32_ref>
<tf.Variable 'Variable_16:0' shape=(2, 3) dtype=int32_ref>


In [4]:
import tensorflow as tf
v1 = tf.constant([[1.0, 2.0], [3.0, 4.0]])
v2 = tf.constant([[5.0, 6.0], [7.0, 8.0]])
with tf.Session() as sess:
    print(v1.eval())

[[ 1.  2.]
 [ 3.  4.]]
